### ISSUE TITLE
The first animation frame doesn't spawn a bullet

### ISSUE THREAD

**Issue by Bios-Marcel** [Bios-Marcel/top-down-pew-pew#1]
Currently the shooting is connected `frame_changed` signal of the players `AnimatedSprite`. Sadly the signal isn't triggered when the first frame plays, therefore a single click will result in a single shooting animation frame that doesn't actually trigger a bullet.

Probably the shooting should be refactored and be done differently. However, the idea behind my approach was, that the shooting is always synchronized with the animation.

**Comment by peterm94** [comment]
I might have a go at this tomorrow if it isn't picked up.

**Comment by Bios-Marcel** [comment]
@peterm94 Currently this task is still available. We shall not work on it ourselves if you want to do it.

**Comment by peterm94** [comment]
This is a bit tricky, if both left and right buttons are pressed at once what is the expected behaviour? I am guessing you want to keep the alternating shooting frames.

**Comment by Bios-Marcel** [comment]
Currently we don't mind. We have one animation for `left`, one for `right` and one for `both`. Sooner or later we might just split the Sprite into 3 parts:

- gun left
- gun right
- character

**Comment by peterm94** [comment]
I have fixed the first frame bullet missing, using the existing frame synchronized trigger implementation. Splitting the sprites would make this a lot nicer to handle.

I would also suggest adding a cooldown on the shooting, it is really easy to spam click faster than the character normally shoots.

**Comment by Bios-Marcel** [comment]
Fixed with https://github.com/Bios-Marcel/top-down-pew-pew/pull/25.
