### ISSUE TITLE
Diagonal movement still incorrect

### ISSUE THREAD

**Issue by LorisSecuro** [Bios-Marcel/top-down-pew-pew#11]
I believe that the solution to the issue #2 does not completely solve the problem of diagonal movement speed.

It limits the maximum speed, but does not limit the acceleration speed.
For example it adds 25 to x and 25 to y when going diagonally instead of 17.677 and 17.677, which still will make diagonal movement slightly faster than it should be.

I've prepared a pull request to address both the acceleration speed and the maximum speed.

**Comment by Bios-Marcel** [comment]
Fixed with beb5959
