### ISSUE TITLE
Walking speed is incorrect when walking diagonally

### ISSUE THREAD

**Issue by Bios-Marcel** [Bios-Marcel/top-down-pew-pew#2]
If you are just walking straight, the speed reaches up to `200` on that axis and stays `0` on the other. However, if you are walking diagonally, then you can reach `200` on both axis, which is way too fast and physically makes no sense.

**Comment by ristic-mladen** [comment]
tell me where the file that controls movement speed is. Multiply by 0.707 when going diagonally and it will remain the same, I don't know the syntax of your language so I don't know where to add it

**Comment by Bios-Marcel** [comment]
@mladenristic1997 
Movement is calculated here: https://github.com/Bios-Marcel/top-down-pew-pew/blob/master/player.gd#L22

The language is Godot Script, a simple and dynamic scripting language.
Docs can be found at https://godot.readthedocs.io/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html

**Comment by ghost** [comment]
Solved with cbdd3cb4d759c86d7d1c52fed6b538097da7b31e
